///////////////////////////////////////////////////////////
//  SubSystemEditModel.cs
//  Implementation of the Class SubSystemEditModel
//  Generated by Enterprise Architect
//  Created on:      12-八月-2015 11:24:14
//  Original author: chicky
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using LC.Model.Entity.Models;
namespace LC.Model.Business.SysManager {
	/// <summary>
	/// 子系统编辑对象
	/// </summary>
	public class SubSystemEditModel : ModelBase {

		/// <summary>
		/// 需要更新修改的子系统信息
		/// </summary>
		private SysSubSystem SubSystem;

        public string SubSystemCode { get; set; }
        public string SubSystemName { get; set; }
        public string Remark { get; set; }
        public string MetroBackColor { get; set; }
        public string MetroForeColor { get; set; }
        public MetroTypes MetroType { get; set; }
        public string IconString { get; set; }
        public List<MenuEditModel> SysMenus { get; set; }

		public SubSystemEditModel(){

		}

		public void InitEditModel(SysSubSystem sysSubSystem)
        {
            this.SubSystem = sysSubSystem;

            this.IconString = sysSubSystem.IconString;
            this.MetroBackColor = sysSubSystem.MetroBackColor;
            this.MetroForeColor = sysSubSystem.MetroForeColor;
            this.MetroType = sysSubSystem.MetroType;
            this.Remark = sysSubSystem.Remark;
            this.SubSystemCode = sysSubSystem.SubSystemCode;
            this.SubSystemName = sysSubSystem.SubSystemName;

            if(sysSubSystem.SysMenus != null && sysSubSystem.SysMenus.Count >0)
            {
                this.SysMenus = new List<MenuEditModel>();
                ICollection<SysMenu> subMenus = sysSubSystem.SysMenus;
                foreach (SysMenu sysmenu in subMenus)
                {
                    MenuEditModel submenu = new MenuEditModel();
                    submenu.InitEditModel(sysmenu);
                    this.SysMenus.Add(submenu);
                }
            }
            else
            {
                this.SysMenus = null;
            }
        }

		/// <summary>
		/// 类型转换string方法
		/// </summary>
		public override string ToString(){

			return "";
		}

	}//end SubSystemEditModel

}//end namespace SysManager